# Generated by Django 5.0.2 on 2024-02-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.IntegerField(choices=[(1, 'Blouse'), (2, 'One-Piece'), (3, 'Jumpsuit'), (4, 'Co-ord Sets')], verbose_name='Categories')),
                ('fabric', models.CharField(max_length=300)),
                ('size', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
